import {SKINS,QUIZ} from './config.js';
import {coins,setCoins,infiniteCoins,ownedSkins,ownSkin,getActiveSkin,setActiveSkin,quizState,saveQuizState} from './storage.js';
import {t,toast,esc,applyThemeAndSkin,localizeStatic} from './ui.js';

const REWARD=20;
function dateKey(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function seededQuestions(){let seed=2166136261;for(const ch of dateKey()){seed^=ch.charCodeAt(0);seed=Math.imul(seed,16777619)>>>0}const a=[...QUIZ];for(let i=a.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,12)}

export class GameSystem{
 constructor(onSkinChange){this.onSkinChange=onSkinChange;this.questions=seededQuestions();this.state=quizState()}
 init(){this.bind();this.renderAll()}
 wallet(){return infiniteCoins()?'∞':String(coins())}
 renderAll(){this.renderWallet();this.renderShop();this.renderMissions()}
 renderWallet(){document.querySelectorAll('[data-wallet]').forEach(n=>n.textContent=this.wallet())}
 renderShop(){const grid=document.querySelector('#skinGrid');if(!grid)return;const owned=ownedSkins(),active=getActiveSkin();grid.innerHTML=Object.entries(SKINS).map(([id,s])=>{const own=owned.includes(id),act=active===id;return `<article class="skin-card card" data-skin-card="${id}"><div class="skin-preview skin-${id}"><span>${esc(s.name)}</span></div><div class="skin-info"><div><h3>${esc(s.name)}</h3><p>${this.description(id)}</p></div><b>${own?t('owned'):`🪙 ${s.price}`}</b></div><button class="skin-action${act?' active':''}" data-skin-action="${id}" ${act?'disabled':''}>${act?t('active'):own?t('equip'):t('buy')}</button></article>`}).join('')}
 description(id){return {default:'La interfaz original, limpia y neutra.',canarias:'Azul, blanco y amarillo, plátanos de fondo y jerga canaria.',lgbt:'Patrón arcoíris y lenguaje inclusivo con terminación en e.',tuna:'Negro, rojo y blanco con guitarras, panderetas y motivos musicales.',aston:'British racing green, detalles lima y estética de competición.',mort:'Crema, marrón, ojazos y una forma de hablar entusiasta y adorable.'}[id]||''}
 renderMissions(){const list=document.querySelector('#missionList'),sum=document.querySelector('#missionSummary');if(!list||!sum)return;this.state=quizState();const done=new Set(this.state.done||[]),first=this.questions.slice(0,6),second=this.questions.slice(6),firstDone=first.filter(q=>done.has(q.id)).length,unlocked=firstDone===6,total=done.size;sum.innerHTML=`<div><strong>${total}/12</strong><span>hechas</span></div><div><strong>${REWARD}</strong><span>🪙 por acierto</span></div><div><strong>240</strong><span>máximo diario</span></div>`;list.innerHTML=`<div class="mission-batch">${first.map((q,i)=>this.card(q,i+1,done)).join('')}</div>${unlocked?`<div class="bonus-heading"><h3>${esc(t('bonusTitle'))}</h3><span>7–12</span></div><div class="mission-batch">${second.map((q,i)=>this.card(q,i+7,done)).join('')}</div>`:`<div class="bonus-gate card">🔒 ${esc(t('bonusLocked'))}</div>`}`}
 card(q,n,done){const complete=done.has(q.id);return `<article class="mission-card card${complete?' done':''}" data-question="${q.id}"><div class="mission-top"><div><small>Misión ${n}</small><h3>${esc(q.q)}</h3></div><b>+${REWARD} 🪙</b></div><div class="mission-options">${q.o.map((o,i)=>`<button data-answer="${i}" ${complete?'disabled':''}>${esc(o)}</button>`).join('')}</div><p class="mission-feedback ${complete?'good':''}">${complete?'✓ '+esc(t('completed')):''}</p></article>`}
 bind(){document.querySelector('#skinGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-skin-action]');if(!b)return;this.handleSkin(b.dataset.skinAction)});document.querySelector('#missionList')?.addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b)return;this.answer(b.closest('[data-question]')?.dataset.question,Number(b.dataset.answer),b)})}
 handleSkin(id){const s=SKINS[id];if(!s)return;const owned=ownedSkins();if(!owned.includes(id)){if(!infiniteCoins()&&coins()<s.price){toast('No tienes suficientes monedas.');return}if(!infiniteCoins())setCoins(coins()-s.price);ownSkin(id)}setActiveSkin(id);applyThemeAndSkin();localizeStatic();this.renderAll();this.onSkinChange?.()}
 answer(id,index,btn){const q=this.questions.find(x=>x.id===id);if(!q||this.state.done?.includes(id))return;const card=btn.closest('.mission-card'),feedback=card.querySelector('.mission-feedback');if(index!==q.a){feedback.className='mission-feedback bad';feedback.textContent=t('tryAgain');btn.classList.add('wrong');return}this.state.done=[...(this.state.done||[]),id];saveQuizState(this.state);if(!infiniteCoins())setCoins(coins()+REWARD);toast(infiniteCoins()?'Correcta · ∞ monedas':`${t('correct')} +${REWARD} 🪙`);this.renderAll()}
}
