import {defaultWeeklyEvents} from './config.js';
import {ensureData,schedules,activeScheduleId,setActiveSchedule,createSchedule,renameSchedule,deleteSchedule,exportPayload,importPayload,storage,setInfiniteCoins} from './storage.js';
import {applyThemeAndSkin,localizeStatic,toast,download,t} from './ui.js';
import {WeeklyPlanner} from './weekly.js';
import {MonthPlanner} from './month.js';
import {GameSystem} from './game.js';

const mobileStyle=document.createElement('link');mobileStyle.rel='stylesheet';mobileStyle.href='./src/mobile.css?v=20';document.head.appendChild(mobileStyle);
ensureData();applyThemeAndSkin();
const weekly=new WeeklyPlanner(),month=new MonthPlanner();
let mobileLocked=matchMedia('(max-width:700px)').matches;
const game=new GameSystem(()=>{localizeStatic();syncLockUI();weekly.render();month.render()});
const VIEWS=['week','month','shop','missions'];
const currentView=()=>storage.get(storage.keys.view,'week');
function setView(view){if(!VIEWS.includes(view))view='week';storage.set(storage.keys.view,view);for(const id of VIEWS)document.getElementById(`${id}View`)?.classList.toggle('hidden',id!==view);document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});document.querySelectorAll('[data-mobile-view]').forEach(b=>b.classList.toggle('active',b.dataset.mobileView===view));document.querySelectorAll('.week-only-action').forEach(n=>n.classList.toggle('hidden',view!=='week'));document.querySelector('#mobileAddBtn')?.classList.toggle('hidden',!['week','month'].includes(view));document.querySelector('.subject-card')?.classList.remove('mobile-sheet-open');window.scrollTo({top:0,behavior:'smooth'})}
function renderScheduleSelect(){const sel=document.querySelector('#scheduleSelect');if(!sel)return;sel.innerHTML=schedules().map(s=>`<option value="${s.id}">${s.name}</option>`).join('');sel.value=activeScheduleId()}
function syncLockUI(){const b=document.querySelector('#mobileEditToggle');if(b){b.setAttribute('aria-pressed',String(!mobileLocked));b.classList.toggle('is-unlocked',!mobileLocked);b.querySelector('.mobile-edit-icon').textContent=mobileLocked?'🔒':'🔓';b.querySelector('.mobile-edit-label').textContent=mobileLocked?t('locked'):t('editing')}weekly.setLocked(mobileLocked);month.setLocked(mobileLocked)}
function setMobileDay(day){const d=Math.max(0,Math.min(4,Number(day)||0));storage.set('planner-mobile-day-v1',String(d));document.querySelectorAll('.mobile-day-tab').forEach((b,i)=>b.classList.toggle('active',i===d));document.querySelectorAll('.day-head,.day-column').forEach(n=>n.classList.toggle('mobile-active',Number(n.dataset.day)===d))}
function bindNavigation(){document.addEventListener('click',e=>{const top=e.target.closest('[data-view]');if(top){setView(top.dataset.view);return}const mobile=e.target.closest('[data-mobile-view]');if(mobile){setView(mobile.dataset.mobileView);return}if(e.target.closest('.subject-chip')&&matchMedia('(max-width:700px)').matches)document.querySelector('.subject-card')?.classList.remove('mobile-sheet-open')});document.querySelector('#mobileEditToggle')?.addEventListener('click',()=>{mobileLocked=!mobileLocked;syncLockUI();toast(mobileLocked?'Edición bloqueada.':'Edición activada.')});document.querySelectorAll('.mobile-day-tab').forEach((b,i)=>b.addEventListener('click',()=>setMobileDay(i)));document.querySelector('#mobileAddBtn')?.addEventListener('click',()=>{if(mobileLocked){toast('Activa la edición arriba para añadir elementos.');return}if(currentView()==='month'){document.querySelector('#addMonthEventBtn')?.click();return}document.querySelector('.subject-card')?.classList.toggle('mobile-sheet-open')})}
function bindSettings(){const back=document.querySelector('#settingsBackdrop'),open=()=>{back.classList.remove('hidden');back.setAttribute('aria-hidden','false')},close=()=>{back.classList.add('hidden');back.setAttribute('aria-hidden','true')};document.querySelector('#settingsBtn')?.addEventListener('click',open);document.querySelector('#mobileSettingsBtn')?.addEventListener('click',open);document.querySelector('#closeSettingsBtn')?.addEventListener('click',close);back?.addEventListener('click',e=>{if(e.target===back)close()});document.querySelector('#scheduleSelect')?.addEventListener('change',e=>{setActiveSchedule(e.target.value);location.reload()});document.querySelector('#newScheduleBtn')?.addEventListener('click',()=>{const name=prompt('Nombre del nuevo horario','Nuevo horario');if(name!==null){createSchedule(name,[]);location.reload()}});document.querySelector('#renameScheduleBtn')?.addEventListener('click',()=>{const cur=schedules().find(s=>s.id===activeScheduleId());const name=prompt('Nuevo nombre',cur?.name||'Horario');if(name){renameSchedule(activeScheduleId(),name);renderScheduleSelect()}});document.querySelector('#deleteScheduleBtn')?.addEventListener('click',()=>{if(confirm('¿Eliminar este horario?')&&deleteSchedule(activeScheduleId()))location.reload()});document.querySelector('#backupScheduleBtn')?.addEventListener('click',()=>download('planificador-backup.json',new Blob([JSON.stringify(exportPayload(),null,2)],{type:'application/json'})));document.querySelector('#importScheduleBtn')?.addEventListener('click',()=>document.querySelector('#importScheduleInput')?.click());document.querySelector('#importScheduleInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{importPayload(JSON.parse(await f.text()));location.reload()}catch{toast('No se pudo importar el archivo.')}});document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{const choice=b.dataset.themeChoice;if(choice==='rosita'&&storage.get(storage.keys.rosita,'0')!=='1'){toast('Desbloquéala con el código rosita.');return}storage.set(storage.keys.theme,choice);applyThemeAndSkin();localizeStatic()}));document.querySelector('#secretCodeForm')?.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#secretCodeInput'),code=input.value.trim().toLowerCase();input.value='';if(code==='lmp'){createSchedule('LMP',defaultWeeklyEvents());location.reload();return}if(code==='rosita'){storage.set(storage.keys.rosita,'1');document.querySelector('[data-theme-choice="rosita"]')?.classList.remove('hidden');storage.set(storage.keys.theme,'rosita');applyThemeAndSkin();toast('Rosita desbloqueada.');return}if(code==='retitos'){setInfiniteCoins(true);game.renderAll();toast('Modo debug: ∞ monedas.');return}toast('Código no válido.')});if(storage.get(storage.keys.rosita,'0')==='1')document.querySelector('[data-theme-choice="rosita"]')?.classList.remove('hidden')}
function bindPWA(){let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.querySelector('#installAppBtn')?.classList.remove('hidden')});document.querySelector('#installAppBtn')?.addEventListener('click',async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;document.querySelector('#installAppBtn')?.classList.add('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
function init(){renderScheduleSelect();localizeStatic();weekly.init();month.init();game.init();bindNavigation();bindSettings();bindPWA();syncLockUI();const def=Math.max(0,Math.min(4,new Date().getDay()-1)),saved=Number(storage.get('planner-mobile-day-v1',String(def)));setMobileDay(saved);setView(currentView());window.addEventListener('storage',()=>{applyThemeAndSkin();localizeStatic()})}
init();window.Planner={weekly,month,game,setView};
