import {SUBJECTS,SUBJECT_BY_ID,MONTH_TYPES} from './config.js';
import {loadMonth,saveMonth,storage,activeScheduleId} from './storage.js';
import {uid,esc,toast,download,t} from './ui.js';

const typeName=id=>MONTH_TYPES.find(x=>x[0]===id)?.[1]||'Otro';
const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseISO=s=>{const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)};

export class MonthPlanner{
 constructor(){this.events=loadMonth();const saved=storage.get(storage.cursorKey(activeScheduleId()),null);this.cursor=saved?parseISO(saved):new Date();this.filters={course:'all',subject:'all',type:'all',status:'all'};this.mobileDate=null;this.locked=matchMedia('(max-width:700px)').matches;}
 init(){this.populate();this.bind();this.render()}
 setLocked(v){this.locked=!!v;['addMonthEventBtn','mobileAgendaAdd'].forEach(id=>{const n=document.getElementById(id);if(n)n.disabled=this.locked})}
 setEvents(v){this.events=v;saveMonth(this.events);this.render()}
 persist(){saveMonth(this.events)}
 populate(){const s=document.querySelector('#monthSubjectFilter');if(s)s.innerHTML='<option value="all">Todas</option>'+SUBJECTS.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');const es=document.querySelector('#eventSubject');if(es)es.innerHTML=SUBJECTS.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');const tf=document.querySelector('#monthTypeFilter');if(tf)tf.innerHTML='<option value="all">Todos</option>'+MONTH_TYPES.map(([id,n])=>`<option value="${id}">${n}</option>`).join('');const et=document.querySelector('#eventType');if(et)et.innerHTML=MONTH_TYPES.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}
 visible(e){const s=SUBJECT_BY_ID[e.subjectId];if(this.filters.course!=='all'&&String(s?.course)!==this.filters.course)return false;if(this.filters.subject!=='all'&&e.subjectId!==this.filters.subject)return false;if(this.filters.type!=='all'&&e.type!==this.filters.type)return false;if(this.filters.status==='pending'&&e.completed)return false;if(this.filters.status==='done'&&!e.completed)return false;return true}
 monthCells(){const y=this.cursor.getFullYear(),m=this.cursor.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset);return Array.from({length:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i))}
 render(){const title=document.querySelector('#monthTitle');if(title)title.textContent=this.cursor.toLocaleDateString('es-ES',{month:'long',year:'numeric'}).replace(/^./,x=>x.toUpperCase());const head=document.querySelector('#monthWeekdayHead');if(head)head.innerHTML=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<b>${x}</b>`).join('');const grid=document.querySelector('#monthGrid');if(!grid)return;const today=localISO(new Date()),currentM=this.cursor.getMonth();grid.innerHTML=this.monthCells().map(d=>{const iso=localISO(d),outside=d.getMonth()!==currentM,evs=this.events.filter(e=>e.date===iso&&this.visible(e));return `<section class="month-day${outside?' outside-month':''}${iso===today?' today':''}${iso===this.mobileDate?' mobile-selected-day':''}" data-date="${iso}"><div class="month-day-head"><span>${d.getDate()}</span><button type="button" data-add-date="${iso}" aria-label="Añadir">+</button></div><div class="month-events">${evs.map(e=>this.chip(e)).join('')}</div></section>`}).join('');this.renderUpcoming();this.renderAgenda();const sum=document.querySelector('#monthFilterSummary');if(sum)sum.textContent=`${this.events.filter(e=>this.visible(e)).length} eventos`}
 chip(e){const s=SUBJECT_BY_ID[e.subjectId],c=s?.color||'#777';return `<button class="month-event-chip${e.completed?' done':''}${e.type==='exam'?' exam':''}" draggable="true" data-month-event-id="${e.id}" style="--subject:${c}" title="${esc(e.title)}"><i></i><span>${esc(e.start?`${e.start} · `:'')}${esc(e.title||typeName(e.type))}</span></button>`}
 renderUpcoming(){const n=document.querySelector('#upcomingList');if(!n)return;const today=localISO(new Date()),items=this.events.filter(e=>!e.completed&&e.date>=today&&this.visible(e)).sort((a,b)=>a.date.localeCompare(b.date)||(a.start||'').localeCompare(b.start||'')).slice(0,8);n.innerHTML=items.length?items.map(e=>`<button class="upcoming-item" data-month-event-id="${e.id}"><b>${esc(e.title)}</b><span>${parseISO(e.date).toLocaleDateString('es-ES',{day:'numeric',month:'short'})}${e.start?' · '+e.start:''}</span></button>`).join(''):'<p class="empty">Sin próximos eventos.</p>'}
 renderAgenda(){const n=document.querySelector('#mobileDayAgenda');if(!n||!matchMedia('(max-width:700px)').matches)return;const iso=this.mobileDate||localISO(new Date()),title=n.querySelector('#mobileAgendaTitle'),list=n.querySelector('#mobileAgendaList');if(title)title.textContent=parseISO(iso).toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});const evs=this.events.filter(e=>e.date===iso&&this.visible(e));if(list)list.innerHTML=evs.length?evs.map(e=>`<button class="mobile-agenda-event" data-month-event-id="${e.id}"><b>${esc(e.title)}</b><span>${e.start||''} ${esc(typeName(e.type))}</span></button>`).join(''):`<button class="mobile-agenda-empty" data-add-date="${iso}">${esc(t('noEvents'))}</button>`}
 bind(){
  document.querySelector('#prevMonthBtn')?.addEventListener('click',()=>{this.cursor=new Date(this.cursor.getFullYear(),this.cursor.getMonth()-1,1);this.saveCursor();this.render()});
  document.querySelector('#nextMonthBtn')?.addEventListener('click',()=>{this.cursor=new Date(this.cursor.getFullYear(),this.cursor.getMonth()+1,1);this.saveCursor();this.render()});
  document.querySelector('#todayMonthBtn')?.addEventListener('click',()=>{this.cursor=new Date();this.mobileDate=localISO(new Date());this.saveCursor();this.render()});
  document.querySelector('#addMonthEventBtn')?.addEventListener('click',()=>this.openForm(this.mobileDate||localISO(new Date())));
  document.querySelector('#monthGrid')?.addEventListener('click',e=>{const add=e.target.closest('[data-add-date]');if(add){this.mobileDate=add.dataset.addDate;if(!this.locked)this.openForm(this.mobileDate);else this.render();return}const chip=e.target.closest('[data-month-event-id]');if(chip){if(this.locked&&matchMedia('(max-width:700px)').matches)return;this.openExisting(chip.dataset.monthEventId);return}const day=e.target.closest('.month-day');if(day){this.mobileDate=day.dataset.date;this.render()}});
  document.querySelector('#monthGrid')?.addEventListener('dragstart',e=>{const chip=e.target.closest('[data-month-event-id]');if(chip)e.dataTransfer.setData('text/event-id',chip.dataset.monthEventId)});
  document.querySelector('#monthGrid')?.addEventListener('dragover',e=>{if(e.target.closest('.month-day'))e.preventDefault()});
  document.querySelector('#monthGrid')?.addEventListener('drop',e=>{const day=e.target.closest('.month-day');if(!day)return;e.preventDefault();if(this.locked)return;const id=e.dataTransfer.getData('text/event-id'),ev=this.events.find(x=>x.id===id);if(ev){ev.date=day.dataset.date;this.persist();this.render()}});
  document.querySelector('#upcomingList')?.addEventListener('click',e=>{const x=e.target.closest('[data-month-event-id]');if(x&&!this.locked)this.openExisting(x.dataset.monthEventId)});
  document.querySelector('#mobileDayAgenda')?.addEventListener('click',e=>{const add=e.target.closest('[data-add-date]');if(add&&!this.locked)this.openForm(add.dataset.addDate);const x=e.target.closest('[data-month-event-id]');if(x&&!this.locked)this.openExisting(x.dataset.monthEventId)});
  document.querySelector('#mobileAgendaAdd')?.addEventListener('click',()=>{if(!this.locked)this.openForm(this.mobileDate||localISO(new Date()))});
  ['monthCourseFilter','monthSubjectFilter','monthTypeFilter','monthStatusFilter'].forEach(id=>document.getElementById(id)?.addEventListener('change',e=>{this.filters[{monthCourseFilter:'course',monthSubjectFilter:'subject',monthTypeFilter:'type',monthStatusFilter:'status'}[id]]=e.target.value;this.render()}));
  document.querySelector('#resetMonthFiltersBtn')?.addEventListener('click',()=>{this.filters={course:'all',subject:'all',type:'all',status:'all'};['monthCourseFilter','monthSubjectFilter','monthTypeFilter','monthStatusFilter'].forEach(id=>document.getElementById(id).value='all');this.render()});
  document.querySelector('#eventForm')?.addEventListener('submit',e=>{e.preventDefault();this.saveForm()});document.querySelector('#closeEventModalBtn')?.addEventListener('click',()=>this.closeForm());document.querySelector('#cancelEventBtn')?.addEventListener('click',()=>this.closeForm());document.querySelector('#deleteEventBtn')?.addEventListener('click',()=>{const id=document.querySelector('#eventId').value;if(!id)return;this.events=this.events.filter(e=>e.id!==id);this.persist();this.closeForm();this.render()});
  document.querySelector('#monthIcsBtn')?.addEventListener('click',()=>this.exportICS());
 }
 saveCursor(){storage.set(storage.cursorKey(activeScheduleId()),localISO(new Date(this.cursor.getFullYear(),this.cursor.getMonth(),1)))}
 openExisting(id){const e=this.events.find(x=>x.id===id);if(!e)return;this.openForm(e.date,e)}
 openForm(date,ev=null){if(this.locked&&matchMedia('(max-width:700px)').matches){toast('Activa la edición para modificar eventos.');return}const b=document.querySelector('#eventModalBackdrop');if(!b)return;document.querySelector('#eventId').value=ev?.id||'';document.querySelector('#eventTitle').value=ev?.title||'';document.querySelector('#eventSubject').value=ev?.subjectId||SUBJECTS[0].id;document.querySelector('#eventType').value=ev?.type||'exam';document.querySelector('#eventDate').value=ev?.date||date;document.querySelector('#eventLocation').value=ev?.location||'';document.querySelector('#eventStart').value=ev?.start||'';document.querySelector('#eventEnd').value=ev?.end||'';document.querySelector('#eventNotes').value=ev?.notes||'';document.querySelector('#eventCompleted').checked=!!ev?.completed;document.querySelector('#eventModalTitle').textContent=ev?'Editar evento':t('newEvent');document.querySelector('#deleteEventBtn').classList.toggle('hidden',!ev);b.classList.remove('hidden');b.setAttribute('aria-hidden','false')}
 closeForm(){const b=document.querySelector('#eventModalBackdrop');b?.classList.add('hidden');b?.setAttribute('aria-hidden','true')}
 saveForm(){const id=document.querySelector('#eventId').value||uid(),old=this.events.find(x=>x.id===id);const e={id,title:document.querySelector('#eventTitle').value.trim()||typeName(document.querySelector('#eventType').value),subjectId:document.querySelector('#eventSubject').value,type:document.querySelector('#eventType').value,date:document.querySelector('#eventDate').value,start:document.querySelector('#eventStart').value,end:document.querySelector('#eventEnd').value,location:document.querySelector('#eventLocation').value.trim(),notes:document.querySelector('#eventNotes').value.trim(),completed:document.querySelector('#eventCompleted').checked};if(old)Object.assign(old,e);else this.events.push(e);this.persist();this.mobileDate=e.date;this.closeForm();this.render()}
 exportICS(){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Planificador//Universidad//ES'];for(const e of this.events){const date=e.date.replaceAll('-','');lines.push('BEGIN:VEVENT',`UID:${e.id}@permutador-lmp`,e.start?`DTSTART:${date}T${e.start.replace(':','')}00`:`DTSTART;VALUE=DATE:${date}`,e.end?`DTEND:${date}T${e.end.replace(':','')}00`:'',`SUMMARY:${(e.title||'Evento').replace(/[\n,;]/g,' ')}`,e.location?`LOCATION:${e.location.replace(/[\n,;]/g,' ')}`:'',e.notes?`DESCRIPTION:${e.notes.replace(/\n/g,'\\n')}`:'','END:VEVENT')}lines.push('END:VCALENDAR');download('calendario-universidad.ics',new Blob([lines.filter(Boolean).join('\r\n')],{type:'text/calendar'}))}
}
