import {SKINS} from './config.js';
import {storage,getActiveSkin} from './storage.js';

const BASE={app:'Planificador',week:'Semana',month:'Mes',shop:'Tienda',missions:'Misiones',settings:'Ajustes',schedule:'Horario',locked:'Bloqueado',editing:'Editando',selected:'Bloque seleccionado',newEvent:'Nuevo evento',newSchedule:'Nuevo horario',all:'Todos',allF:'Todas',pending:'Pendientes',done:'Completados',filters:'Filtros',reset:'Restablecer',add:'Añadir',shopTitle:'Tienda de skins',shopIntro:'Consigue monedas completando misiones y desbloquea nuevos aspectos.',missionTitle:'Misiones del día',missionIntro:'Responde preguntas tipo test. Cada acierto da monedas.',owned:'Comprada',equip:'Equipar',active:'Activa',buy:'Comprar',coins:'monedas',completed:'Completada. Monedas cobradas.',tryAgain:'Esa no era. Prueba otra.',correct:'Respuesta correcta.',bonusLocked:'Completa las 6 primeras misiones para desbloquear otros 6 retos.',bonusTitle:'Segunda tanda desbloqueada',noEvents:'Nada apuntado. Toca para añadir algo.'};
const CANARIAS={app:'Planificador, chacho',week:'La semanita',month:'El mes',shop:'Tiendita',missions:'Retitos',settings:'Ajustes, mi niño',locked:'Quietito',editing:'Dándole caña',selected:'Bloque pillado',add:'Añadir, chacho',shopTitle:'Tiendita de skins',shopIntro:'Haz unos retitos y gana perras pa desbloquear skins.',missionTitle:'Retitos del día',missionIntro:'Contesta bien, mi niño, y te llevas moneditas.',tryAgain:'Ños, esa no era. Prueba otra.',correct:'¡Mi niño, clavada!',bonusLocked:'Termina los 6 primeros retitos y te salen otros 6.',bonusTitle:'Más retitos, chacho',noEvents:'Aquí no hay nada, mi niño.'};
const MORT={app:'¡Mi plan precioso!',week:'¡Semanita!',month:'¡Mes precioso!',shop:'¡Tesoooros!',missions:'¡Preguntitas!',settings:'Cositas',locked:'No tocar, porfi',editing:'¡Estoy ayudando!',selected:'¡Mi bloque bonito!',add:'¡Pon otra cosita!',shopTitle:'¡Tesoooros preciosos!',shopIntro:'¡Moneditas! ¡Skins! ¡Qué emoción!',missionTitle:'¡Preguntitas preciosas!',missionIntro:'Si aciertas, salen moneditas. ¡MONEDITAS!',tryAgain:'Oh... no era esa. ¿Otra vez? ¡Sí!',correct:'¡SÍÍÍ! ¡Lo hiciste!',bonusLocked:'Primero seis preguntitas... y luego ¡MÁS!',bonusTitle:'¡Más preguntitas! ¡Qué felicidad!',noEvents:'Está vacíooo... podemos poner una cosita.'};
function inclusiveWord(s){const fixed={Todos:'Todes',Todas:'Todes',Completados:'Completades',Bloqueado:'Bloqueade',Editando:'Editande','Bloque seleccionado':'Bloque seleccionade','Nuevo evento':'Nueve evente','Nuevo horario':'Nueve horarie','Tienda de skins':'Tienda de skins inclusives','Misiones del día':'Misiones del día para todes'};if(fixed[s])return fixed[s];return s.replace(/\bmonedas\b/gi,'monedes').replace(/\bacierto\b/gi,'acierte').replace(/\bpreguntas\b/gi,'preguntes').replace(/\bCompletada\b/g,'Completade').replace(/\bnuevos\b/g,'nueves').replace(/\bnuevas\b/g,'nueves').replace(/\btodos\b/gi,'todes').replace(/\btodas\b/gi,'todes')}
export function t(key){const skin=getActiveSkin();let text=(skin==='canarias'?CANARIAS[key]:skin==='mort'?MORT[key]:null)||BASE[key]||key;if(skin==='lgbt')text=inclusiveWord(text);return text}
export function applyThemeAndSkin(){const skin=getActiveSkin();document.body.dataset.skin=skin;document.documentElement.dataset.skin=skin;let theme=storage.get(storage.keys.theme,'system');if(theme==='rosita'&&storage.get(storage.keys.rosita,'0')!=='1')theme='system';if(theme==='system')theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',skin==='aston'?'#00352f':theme==='dark'?'#111318':'#f6f7fb');const pattern=document.querySelector('#skinPattern');if(pattern){const p=SKINS[skin]?.pattern||'';pattern.textContent=p?(`${p} `.repeat(90)):'';pattern.classList.toggle('hidden',!p)}}
export function localizeStatic(){const map={'#appTitle':'app','#tabWeek':'week','#tabMonth':'month','#tabShop':'shop','#tabMissions':'missions','#settingsBtnText':'settings','#scheduleLabel':'schedule','#editorHeading':'selected','#addMonthEventBtn':'newEvent','#settingsTitle':'settings','#newScheduleBtn':'newSchedule','#shopHeading':'shopTitle','#shopIntro':'shopIntro','#missionsHeading':'missionTitle','#missionsIntro':'missionIntro'};for(const [sel,key] of Object.entries(map)){const n=document.querySelector(sel);if(n)n.textContent=t(key)}const lock=document.querySelector('#mobileEditToggle .mobile-edit-label');if(lock&&document.querySelector('#mobileEditToggle'))lock.textContent=document.querySelector('#mobileEditToggle').getAttribute('aria-pressed')==='true'?t('editing'):t('locked')}
export function toast(message,ms=1800){const n=document.querySelector('#toast');if(!n)return;n.textContent=message;n.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.classList.remove('show'),ms)}
export function download(name,blob){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
export const uid=()=>crypto.randomUUID?.()||`id_${Date.now()}_${Math.random().toString(36).slice(2)}`;
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
