import {DAYS,SUBJECTS,SUBJECT_BY_ID,START_HOUR,SLOT_MIN,SLOTS} from './config.js';
import {loadWeekly,saveWeekly,storage} from './storage.js';
import {uid,clamp,toast,download,esc,t} from './ui.js';

const slotToTime=s=>{const min=START_HOUR*60+s*SLOT_MIN;return `${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`};
const overlap=(a,b)=>a.startSlot<b.startSlot+b.duration&&b.startSlot<a.startSlot+a.duration;

export class WeeklyPlanner{
 constructor(){this.events=loadWeekly();this.selected=new Set();this.undo=[];this.locked=matchMedia('(max-width:700px)').matches;this.filters={lab:'all',course:'all',subject:'all',frame:'all',frameColor:'all'};this.showNow=storage.get('weekly-planner-show-current-time','1')!=='0';this.drag=null;}
 init(){this.renderTimes();this.renderSubjects();this.bind();this.render();this.updateNow();this.nowTimer=setInterval(()=>this.updateNow(),30000);}
 destroy(){clearInterval(this.nowTimer)}
 snapshot(){this.undo.push(JSON.stringify(this.events));if(this.undo.length>60)this.undo.shift();document.querySelector('#undoBtn').disabled=!this.undo.length}
 persist(){saveWeekly(this.events)}
 mutate(fn){if(this.locked&&matchMedia('(max-width:700px)').matches){toast('Activa la edición para modificar el horario.');return}this.snapshot();fn();this.persist();this.render()}
 setLocked(v){this.locked=!!v;document.querySelector('#editor')?.classList.toggle('locked',this.locked);['earlierBtn','laterBtn','shorterBtn','longerBtn','deleteSelectedBtn'].forEach(id=>{const b=document.getElementById(id);if(b)b.disabled=this.locked});}
 setEvents(events){this.events=events;this.selected.clear();this.persist();this.render()}

 renderTimes(){const c=document.querySelector('#timeColumn');if(!c)return;c.innerHTML='';for(let s=0;s<SLOTS;s++){const n=document.createElement('div');n.className='time-label';n.textContent=s%2===0?slotToTime(s):'';c.appendChild(n)}}
 renderSubjects(){const c=document.querySelector('#subjectList');if(!c)return;c.innerHTML=SUBJECTS.map(s=>`<button class="subject-chip" draggable="true" data-subject="${s.id}" style="--subject:${s.color}"><span></span><b>${esc(s.name)}</b><small>${s.course}.º</small></button>`).join('');
   const sel=document.querySelector('#subjectFilter');if(sel)sel.innerHTML=`<option value="all">Todas</option>`+SUBJECTS.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
 }
 lanes(dayEvents){const items=[...dayEvents].sort((a,b)=>a.startSlot-b.startSlot||b.duration-a.duration);const groups=[];for(const e of items){let g=groups.find(g=>g.some(x=>overlap(x,e)));if(!g){g=[];groups.push(g)}g.push(e)}const out=new Map();for(const g of groups){const lanes=[];for(const e of g){let lane=lanes.findIndex(last=>last<=e.startSlot);if(lane<0){lane=lanes.length;lanes.push(0)}lanes[lane]=e.startSlot+e.duration;out.set(e.id,{lane,count:lanes.length})}for(const e of g){const x=out.get(e.id);x.count=Math.max(x.count,lanes.length)}}return out}
 visible(e){const s=SUBJECT_BY_ID[e.subjectId];if(!s)return false;if(this.filters.lab==='lab'&&!e.lab)return false;if(this.filters.lab==='nonlab'&&e.lab)return false;if(this.filters.course!=='all'&&String(s.course)!==this.filters.course)return false;if(this.filters.subject!=='all'&&e.subjectId!==this.filters.subject)return false;if(this.filters.frame==='framed'&&!e.frame)return false;if(this.filters.frame==='none'&&e.frame)return false;if(this.filters.frameColor!=='all'&&e.frame!==this.filters.frameColor)return false;return true}
 render(){for(let d=0;d<5;d++){const col=document.querySelector(`.day-column[data-day="${d}"]`);if(!col)continue;const events=this.events.filter(e=>e.day===d&&this.visible(e));const lanes=this.lanes(events);col.innerHTML='';for(const e of events){const s=SUBJECT_BY_ID[e.subjectId];if(!s)continue;const {lane,count}=lanes.get(e.id)||{lane:0,count:1};const n=document.createElement('article');n.className=`week-event${e.lab?' lab':''}${this.selected.has(e.id)?' selected':''}`;n.dataset.id=e.id;n.style.setProperty('--subject',s.color);n.style.top=`calc(var(--slot-h) * ${e.startSlot})`;n.style.height=`calc(var(--slot-h) * ${e.duration} - 2px)`;n.style.left=`calc(${lane} * (100% / ${count}))`;n.style.width=`calc(100% / ${count} - 2px)`;n.style.opacity=e.opacity??1;if(e.frame)n.dataset.frame=e.frame;n.innerHTML=`<strong>${esc(s.name)}</strong>${e.lab?'<em>LAB</em>':''}<small>${slotToTime(e.startSlot)}–${slotToTime(e.startSlot+e.duration)}</small><i class="resize-handle"></i>`;col.appendChild(n)}}this.renderEditor();this.updateFilterSummary()}
 renderEditor(){const ed=document.querySelector('#editor'),title=document.querySelector('#editorTitle');if(!ed||!title)return;const ids=[...this.selected];if(!ids.length){ed.classList.add('hidden');return}ed.classList.remove('hidden');const first=this.events.find(e=>e.id===ids[0]);title.textContent=ids.length>1?`${ids.length} bloques seleccionados`:SUBJECT_BY_ID[first?.subjectId]?.name||'';ed.classList.toggle('locked',this.locked)}
 updateFilterSummary(){const n=document.querySelector('#filterSummary');if(n)n.textContent=`Mostrando ${this.events.filter(e=>this.visible(e)).length} de ${this.events.length} bloques.`}

 bind(){
   document.querySelector('#subjectList')?.addEventListener('dragstart',e=>{const chip=e.target.closest('[data-subject]');if(!chip)return;e.dataTransfer.setData('text/plain',chip.dataset.subject)});
   document.querySelectorAll('.day-column').forEach(col=>{col.addEventListener('dragover',e=>e.preventDefault());col.addEventListener('drop',e=>{e.preventDefault();if(this.locked&&matchMedia('(max-width:700px)').matches)return;const subjectId=e.dataTransfer.getData('text/plain');if(!SUBJECT_BY_ID[subjectId])return;const r=col.getBoundingClientRect();const slot=clamp(Math.floor((e.clientY-r.top)/(r.height/SLOTS)),0,SLOTS-1);this.mutate(()=>this.events.push({id:uid(),day:Number(col.dataset.day),subjectId,startSlot:slot,duration:2,lab:false,frame:null,opacity:1}))});col.addEventListener('click',e=>{if(e.target!==col)return;const selectedSubject=document.querySelector('.subject-chip.selected')?.dataset.subject;if(!selectedSubject||this.locked&&matchMedia('(max-width:700px)').matches)return;const r=col.getBoundingClientRect(),slot=clamp(Math.floor((e.clientY-r.top)/(r.height/SLOTS)),0,SLOTS-1);this.mutate(()=>this.events.push({id:uid(),day:Number(col.dataset.day),subjectId:selectedSubject,startSlot:slot,duration:2,lab:false,frame:null,opacity:1}))})});
   document.querySelector('#subjectList')?.addEventListener('click',e=>{const chip=e.target.closest('[data-subject]');if(!chip)return;document.querySelectorAll('.subject-chip').forEach(x=>x.classList.toggle('selected',x===chip))});

   document.querySelector('#calendar')?.addEventListener('click',e=>{const n=e.target.closest('.week-event');if(!n)return;if(e.ctrlKey||e.metaKey||e.shiftKey){this.selected.has(n.dataset.id)?this.selected.delete(n.dataset.id):this.selected.add(n.dataset.id)}else{this.selected.clear();this.selected.add(n.dataset.id)}this.render()});
   document.querySelector('#calendar')?.addEventListener('contextmenu',e=>{const n=e.target.closest('.week-event');if(!n)return;e.preventDefault();if(!this.selected.has(n.dataset.id)){this.selected.clear();this.selected.add(n.dataset.id)}this.render();this.openContext(e.clientX,e.clientY)});
   document.querySelector('#calendar')?.addEventListener('pointerdown',e=>this.pointerDown(e));

   const edit=(id,fn)=>document.querySelector(id)?.addEventListener('click',()=>this.mutate(()=>{for(const eid of this.selected){const ev=this.events.find(x=>x.id===eid);if(ev)fn(ev)}}));
   edit('#earlierBtn',ev=>ev.startSlot=clamp(ev.startSlot-1,0,SLOTS-ev.duration));edit('#laterBtn',ev=>ev.startSlot=clamp(ev.startSlot+1,0,SLOTS-ev.duration));edit('#shorterBtn',ev=>ev.duration=Math.max(1,ev.duration-1));edit('#longerBtn',ev=>ev.duration=Math.min(SLOTS-ev.startSlot,ev.duration+1));
   document.querySelector('#deleteSelectedBtn')?.addEventListener('click',()=>this.mutate(()=>{this.events=this.events.filter(e=>!this.selected.has(e.id));this.selected.clear()}));
   document.querySelector('#undoBtn')?.addEventListener('click',()=>{const last=this.undo.pop();if(!last)return;this.events=JSON.parse(last);this.persist();this.selected.clear();this.render();document.querySelector('#undoBtn').disabled=!this.undo.length});
   document.querySelector('#clearBtn')?.addEventListener('click',()=>{if(confirm('¿Vaciar el horario semanal?'))this.mutate(()=>{this.events=[];this.selected.clear()})});
   document.querySelector('#nowToggleBtn')?.addEventListener('click',()=>{this.showNow=!this.showNow;storage.set('weekly-planner-show-current-time',this.showNow?'1':'0');document.querySelector('#nowToggleBtn').classList.toggle('active',this.showNow);this.updateNow()});
   ['labFilter','courseFilter','subjectFilter','frameFilter'].forEach(id=>document.getElementById(id)?.addEventListener('change',e=>{const key={labFilter:'lab',courseFilter:'course',subjectFilter:'subject',frameFilter:'frame'}[id];this.filters[key]=e.target.value;this.render()}));
   document.querySelector('#resetFiltersBtn')?.addEventListener('click',()=>{this.filters={lab:'all',course:'all',subject:'all',frame:'all',frameColor:'all'};['labFilter','courseFilter','subjectFilter','frameFilter'].forEach(id=>{const n=document.getElementById(id);if(n)n.value='all'});this.render()});
   document.querySelector('#exportBtn')?.addEventListener('click',()=>this.export(document.querySelector('#exportType')?.value||'png'));
   document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))document.querySelector('#contextMenu')?.classList.add('hidden')});
 }

 pointerDown(e){const n=e.target.closest('.week-event');if(!n)return;if(this.locked&&matchMedia('(max-width:700px)').matches)return;const ev=this.events.find(x=>x.id===n.dataset.id);if(!ev)return;const resize=e.target.closest('.resize-handle');const start={x:e.clientX,y:e.clientY,ev:{...ev},resize:!!resize,day:ev.day};let moved=false;const move=me=>{if(Math.abs(me.clientX-start.x)+Math.abs(me.clientY-start.y)<5)return;moved=true;const col=n.closest('.day-column'),r=col.getBoundingClientRect();const delta=Math.round((me.clientY-start.y)/(r.height/SLOTS));if(start.resize)ev.duration=clamp(start.ev.duration+delta,1,SLOTS-ev.startSlot);else{ev.startSlot=clamp(start.ev.startSlot+delta,0,SLOTS-ev.duration);const el=document.elementFromPoint(me.clientX,me.clientY)?.closest('.day-column');if(el)ev.day=Number(el.dataset.day)}this.render()};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);if(moved){this.snapshot();this.persist();this.render()}};addEventListener('pointermove',move);addEventListener('pointerup',up,{once:true})}

 openContext(x,y){const m=document.querySelector('#contextMenu');if(!m)return;m.style.left=`${x}px`;m.style.top=`${y}px`;m.classList.remove('hidden');m.onclick=e=>{const a=e.target.closest('[data-action]');if(!a)return;const action=a.dataset.action;m.classList.add('hidden');if(action==='lab')this.mutate(()=>this.selected.forEach(id=>{const ev=this.events.find(x=>x.id===id);if(ev)ev.lab=!ev.lab}));if(action.startsWith('frame-'))this.mutate(()=>this.selected.forEach(id=>{const ev=this.events.find(x=>x.id===id);if(ev)ev.frame=action==='frame-none'?null:action.slice(6)}));if(action==='opacity')this.mutate(()=>this.selected.forEach(id=>{const ev=this.events.find(x=>x.id===id);if(ev)ev.opacity=(ev.opacity??1)>.7?.55:1}));if(action==='duplicate')this.mutate(()=>{const clones=this.events.filter(ev=>this.selected.has(ev.id)).map(ev=>({...ev,id:uid(),startSlot:clamp(ev.startSlot+1,0,SLOTS-ev.duration)}));this.events.push(...clones);this.selected=new Set(clones.map(x=>x.id))});if(action==='delete')this.mutate(()=>{this.events=this.events.filter(ev=>!this.selected.has(ev.id));this.selected.clear()})}}

 updateNow(){const line=document.querySelector('#currentTimeLine');if(!line)return;if(!this.showNow){line.classList.add('hidden');return}const d=new Date(),weekday=d.getDay()-1,min=d.getHours()*60+d.getMinutes(),start=START_HOUR*60,end=(START_HOUR+SLOTS/2)*60;if(weekday<0||weekday>4||min<start||min>end){line.classList.add('hidden');return}line.classList.remove('hidden');line.style.setProperty('--now-day',weekday);line.style.setProperty('--now-y',`${((min-start)/(end-start))*100}%`);line.querySelector('span').textContent=`Ahora · ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}

 svg(){const W=1200,H=820,left=80,top=60,row=(H-top-20)/SLOTS,col=(W-left-20)/5;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="white"/><style>text{font-family:Arial,sans-serif;fill:#111}.sm{font-size:11px}.hd{font-size:14px;font-weight:700}</style>`;DAYS.forEach((d,i)=>s+=`<text class="hd" x="${left+i*col+8}" y="35">${d}</text>`);for(let k=0;k<=SLOTS;k++){const y=top+k*row;s+=`<line x1="${left}" x2="${W-20}" y1="${y}" y2="${y}" stroke="#ddd"/>`;if(k<SLOTS&&k%2===0)s+=`<text class="sm" x="8" y="${y+12}">${slotToTime(k)}</text>`}for(let i=0;i<=5;i++){const x=left+i*col;s+=`<line y1="${top}" y2="${H-20}" x1="${x}" x2="${x}" stroke="#ddd"/>`}for(const e of this.events){const sub=SUBJECT_BY_ID[e.subjectId];if(!sub)continue;const x=left+e.day*col+2,y=top+e.startSlot*row+1,w=col-4,h=e.duration*row-2;s+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="6" fill="${sub.color}" opacity=".9"/><text class="sm" x="${x+6}" y="${y+15}" fill="white">${esc(sub.name.slice(0,34))}${e.lab?' · LAB':''}</text>`}return s+'</svg>'}
 export(type){if(type==='svg'){download('horario.svg',new Blob([this.svg()],{type:'image/svg+xml'}));return}if(type==='html-live'){const html=`<!doctype html><meta charset="utf-8"><title>Horario</title><body>${this.svg()}<script>setInterval(()=>location.reload(),60000)<\/script></body>`;download('horario-interactivo.html',new Blob([html],{type:'text/html'}));return}if(type==='xlsx'){const rows=[['Día','Asignatura','Inicio','Fin','LAB'],...this.events.map(e=>[DAYS[e.day],SUBJECT_BY_ID[e.subjectId]?.name||'',slotToTime(e.startSlot),slotToTime(e.startSlot+e.duration),e.lab?'Sí':'No'])];const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Horario"><Table>${rows.map(r=>`<Row>${r.map(c=>`<Cell><Data ss:Type="String">${esc(c)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;download('horario.xls',new Blob([xml],{type:'application/vnd.ms-excel'}));return}if(type==='pdf'){const w=open('','_blank');w.document.write(`<title>Horario</title>${this.svg()}<script>onload=()=>print()<\/script>`);w.document.close();return}const img=new Image(),svg=this.svg(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));img.onload=()=>{const c=document.createElement('canvas');c.width=1200;c.height=820;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);URL.revokeObjectURL(url);c.toBlob(b=>download(`horario.${type==='jpg'?'jpg':'png'}`,b),type==='jpg'?'image/jpeg':'image/png',.92)};img.src=url}
}
